<%--
  Created by IntelliJ IDEA.
  User: 이상화
  Date: 2018-04-24
  Time: 오후 4:57
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" isErrorPage="true" %>
<html>
<head>
    <title>에러페이지</title>
</head>
<style type="text/css">
    body{
        background-color: blue;
        color:red;
    }
</style>
<body>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
<hr>
<h1>ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR에러ERROR</h1>
<hr>
</body>
</html>
